// =========================================================================
// Copyright 2019 EPAM Systems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =========================================================================

using Android.App;
using Android.Content;
using Android.OS;
using FlexiMvvm.ViewModels;

namespace FlexiMvvm.Views
{
    /// <summary>
    /// Defines the contract for a platform-specific view that participates in navigation.
    /// </summary>
    /// <typeparam name="TViewModel">The type of the view model.</typeparam>
    public interface INavigationView<out TViewModel> : IView<TViewModel>
        where TViewModel : class, ILifecycleViewModel
    {
        /// <summary>
        /// Gets the request code that generates a unique numeric code to pass as argument to the <see cref="StartActivityForResult(Intent,int)"/> method.
        /// </summary>
        RequestCode RequestCode { get; }

        /// <summary>
        /// Launch a new activity.
        /// </summary>
        /// <param name="intent">The intent to start.</param>
        void StartActivity(Intent intent);

        /// <summary>
        /// Launches a new activity.
        /// </summary>
        /// <param name="intent">The intent to start.</param>
        /// <param name="options">Additional options for how the <see cref="Activity"/> should be started. Can be <see langword="null"/>.</param>
        void StartActivity(Intent intent, Bundle? options);

        /// <summary>
        /// Launches an activity for which you would like a result when it finished.
        /// Using a negative <paramref name="requestCode"/> is the same as calling <see cref="StartActivity(Intent)"/>.
        /// </summary>
        /// <param name="intent">The intent to start.</param>
        /// <param name="requestCode">A unique numeric code generated by the <see cref="RequestCode"/> property.</param>
        void StartActivityForResult(Intent intent, int requestCode);

        /// <summary>
        /// Launches an activity for which you would like a result when it finished.
        /// Using a negative <paramref name="requestCode"/> is the same as calling <see cref="StartActivity(Intent)"/>.
        /// </summary>
        /// <param name="intent">The intent to start.</param>
        /// <param name="requestCode">A unique numeric code generated by the <see cref="RequestCode"/> property.</param>
        /// <param name="options">Additional options for how the <see cref="Activity"/> should be started. Can be <see langword="null"/>.</param>
        void StartActivityForResult(Intent intent, int requestCode, Bundle? options);

        /// <summary>
        /// Sets the lifecycle-aware view model result to be returned to the calling view's model.
        /// </summary>
        /// <param name="resultCode">Determines whether the result should be set as successful or not due to cancellation by the user.</param>
        /// <param name="data">Contains a set of key/value pairs that is used as source data for the view model result. Can be <see langword="null"/>.</param>
        void SetResult(Android.App.Result resultCode, Intent? data);

        /// <summary>
        /// Handles the lifecycle-aware view model result.
        /// </summary>
        /// <param name="requestCode">A unique numeric code generated by the <see cref="RequestCode"/> property.</param>
        /// <param name="resultCode">Determines whether the view model result is set successfully or not due to cancellation by the user.</param>
        /// <param name="data">Contains a set of key/value pairs that is used as source data for the view model result. Can be <see langword="null"/>.</param>
        void OnActivityResult(int requestCode, Android.App.Result resultCode, Intent? data);
    }
}
