// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FlexiMvvm.Views.Generation.Ios
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ViewsGenerator : ViewsGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"

// =========================================================================
// Copyright 2019 EPAM Systems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =========================================================================

            
            #line default
            #line hidden
            this.Write("#nullable enable\r\n\r\n");
            this.Write("using System;\r\nusing System.Diagnostics.CodeAnalysis;\r\nusing System.Threading.Tas" +
                    "ks;\r\nusing FlexiMvvm.ViewModels;\r\nusing FlexiMvvm.Views.Core;\r\nusing FlexiMvvm.V" +
                    "iews.Keyboard;\r\nusing Foundation;\r\nusing UIKit;\r\n");
            
            #line 29 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
 foreach (var viewGenerationOptions in ViewsGenerationOptions) { 
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 31 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetNamespace(viewGenerationOptions)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// Represents the <see cref=\"");
            
            #line 34 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.BaseClassName));
            
            #line default
            #line hidden
            this.Write("\"/> that is adapted for use with the FlexiMvvm.\r\n    /// </summary>\r\n    public p" +
                    "artial class ");
            
            #line 36 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 36 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.BaseClassName));
            
            #line default
            #line hidden
            this.Write(", IIosView\r\n    {\r\n        private KeyboardHandler? _keyboardHandler;\r\n\r\n        " +
                    "/// <inheritdoc />\r\n        public ");
            
            #line 41 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 43 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public ");
            
            #line 47 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSCoder coder)\r\n            : base(coder)\r\n        {\r\n            LifecycleDeleg" +
                    "ate = new ViewLifecycleDelegate<");
            
            #line 50 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public ");
            
            #line 54 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(string nibName, NSBundle bundle)\r\n            : base(nibName, bundle)\r\n        {" +
                    "\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 57 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        protected ");
            
            #line 61 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSObjectFlag t)\r\n            : base(t)\r\n        {\r\n            LifecycleDelegate" +
                    " = new ViewLifecycleDelegate<");
            
            #line 64 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        protected internal ");
            
            #line 68 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(IntPtr handle)\r\n            : base(handle)\r\n        {\r\n            LifecycleDele" +
                    "gate = new ViewLifecycleDelegate<");
            
            #line 71 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(">(this);\r\n        }\r\n\r\n        /// <summary>\r\n        /// Gets the view lifecycle" +
                    " delegate. Intended for internal use by the FlexiMvvm.\r\n        /// </summary>\r\n" +
                    "        protected virtual IViewLifecycleDelegate LifecycleDelegate { get; }\r\n\r\n");
            
            #line 79 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
      if (viewGenerationOptions.HandleKeyboard) { 
            
            #line default
            #line hidden
            this.Write("        /// <inheritdoc />\r\n        public virtual IKeyboardHandler? KeyboardHand" +
                    "ler => _keyboardHandler ??= Keyboard.KeyboardHandler.Create(View);\r\n");
            
            #line 82 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("        /// <inheritdoc />\r\n        public virtual IKeyboardHandler? KeyboardHand" +
                    "ler => _keyboardHandler;\r\n");
            
            #line 85 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
      } 
            
            #line default
            #line hidden
            this.Write("\r\n        /// <inheritdoc />\r\n        public override void WillMoveToParentViewCo" +
                    "ntroller(UIViewController? parent)\r\n        {\r\n            base.WillMoveToParent" +
                    "ViewController(parent);\r\n\r\n            LifecycleDelegate.WillMoveToParentViewCon" +
                    "troller(parent);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public overri" +
                    "de void ViewDidLoad()\r\n        {\r\n            base.ViewDidLoad();\r\n\r\n           " +
                    " LifecycleDelegate.ViewDidLoad();\r\n        }\r\n\r\n        /// <inheritdoc />\r\n    " +
                    "    public override void ViewWillAppear(bool animated)\r\n        {\r\n            b" +
                    "ase.ViewWillAppear(animated);\r\n\r\n            LifecycleDelegate.ViewWillAppear();" +
                    "\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public override void ViewDidA" +
                    "ppear(bool animated)\r\n        {\r\n            base.ViewDidAppear(animated);\r\n\r\n  " +
                    "          LifecycleDelegate.ViewDidAppear();\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        public override void ViewWillDisappear(bool animated)\r\n        {\r" +
                    "\n            base.ViewWillDisappear(animated);\r\n\r\n            LifecycleDelegate." +
                    "ViewWillDisappear();\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public ov" +
                    "erride void ViewDidDisappear(bool animated)\r\n        {\r\n            base.ViewDid" +
                    "Disappear(animated);\r\n\r\n            LifecycleDelegate.ViewDidDisappear();\r\n     " +
                    "   }\r\n\r\n        /// <inheritdoc />\r\n        public override void DidMoveToParent" +
                    "ViewController(UIViewController? parent)\r\n        {\r\n            base.DidMoveToP" +
                    "arentViewController(parent);\r\n\r\n            LifecycleDelegate.DidMoveToParentVie" +
                    "wController(parent);\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Represents " +
                    "the <see cref=\"");
            
            #line 145 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.BaseClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> that is adapted for use with the FlexiMvvm
    /// and has its own lifecycle-aware view model.
    /// </summary>
    /// <typeparam name=""TViewModel"">The type of the view model.</typeparam>
    [SuppressMessage(
        ""Compiler"",
        ""CS8618:Non-nullable field is uninitialized."",
        Justification = ""The view lifecycle delegate sets a value to the ViewModel property so it is never null."")]
    public partial class ");
            
            #line 153 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel> : ");
            
            #line 153 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(", INavigationView<TViewModel>, ILifecycleViewModelOwner<TViewModel>\r\n        wher" +
                    "e TViewModel : class, ILifecycleViewModelWithoutParameters\r\n    {\r\n        /// <" +
                    "inheritdoc />\r\n        public ");
            
            #line 157 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 159 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n      " +
                    "  public ");
            
            #line 163 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSCoder coder)\r\n            : base(coder)\r\n        {\r\n            LifecycleDeleg" +
                    "ate = new ViewLifecycleDelegate<");
            
            #line 166 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n      " +
                    "  public ");
            
            #line 170 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(string nibName, NSBundle bundle)\r\n            : base(nibName, bundle)\r\n        {" +
                    "\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 173 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n      " +
                    "  protected ");
            
            #line 177 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSObjectFlag t)\r\n            : base(t)\r\n        {\r\n            LifecycleDelegate" +
                    " = new ViewLifecycleDelegate<");
            
            #line 180 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n      " +
                    "  protected internal ");
            
            #line 184 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(IntPtr handle)\r\n            : base(handle)\r\n        {\r\n            LifecycleDele" +
                    "gate = new ViewLifecycleDelegate<");
            
            #line 187 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n      " +
                    "  public event EventHandler<ResultSetEventArgs> ResultSet;\r\n\r\n        /// <inher" +
                    "itdoc />\r\n        protected override IViewLifecycleDelegate LifecycleDelegate { " +
                    "get; }\r\n\r\n        /// <inheritdoc />\r\n        public TViewModel ViewModel { get;" +
                    " private set; }\r\n\r\n        /// <inheritdoc />\r\n        public void SetResult(Res" +
                    "ultCode resultCode, Result? result)\r\n        {\r\n            LifecycleDelegate.Se" +
                    "tResult(resultCode, result);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        p" +
                    "ublic void RaiseResultSet(ResultCode resultCode, Result? result)\r\n        {\r\n   " +
                    "         ResultSet?.Invoke(this, new ResultSetEventArgs(resultCode, result));\r\n " +
                    "       }\r\n\r\n        /// <inheritdoc />\r\n        public void HandleResult(object " +
                    "sender, ResultSetEventArgs args)\r\n        {\r\n            if (sender == null)\r\n  " +
                    "              throw new ArgumentNullException(nameof(sender));\r\n            if (" +
                    "args == null)\r\n                throw new ArgumentNullException(nameof(args));\r\n\r" +
                    "\n            LifecycleDelegate.HandleResult(sender, args);\r\n        }\r\n\r\n       " +
                    " /// <inheritdoc />\r\n        void ILifecycleViewModelOwner<TViewModel>.SetViewMo" +
                    "del(TViewModel viewModel)\r\n        {\r\n            ViewModel = viewModel ?? throw" +
                    " new ArgumentNullException(nameof(viewModel));\r\n        }\r\n\r\n        /// <inheri" +
                    "tdoc />\r\n        async Task ILifecycleViewModelOwner<TViewModel>.InitializeViewM" +
                    "odelAsync(bool recreated)\r\n        {\r\n            await ViewModel.InitializeAsyn" +
                    "c(recreated);\r\n        }\r\n    }\r\n\r\n    /// <summary>\r\n    /// Represents the <se" +
                    "e cref=\"");
            
            #line 236 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.BaseClassName));
            
            #line default
            #line hidden
            this.Write(@"""/> that is adapted for use with the FlexiMvvm,
    /// has its own lifecycle-aware view model and takes lifecycle-aware view model parameters.
    /// </summary>
    /// <typeparam name=""TViewModel"">The type of the view model.</typeparam>
    /// <typeparam name=""TParameters"">The type of the view model parameters.</typeparam>
    [SuppressMessage(
        ""Compiler"",
        ""CS8618:Non-nullable field is uninitialized."",
        Justification = ""The view lifecycle delegate sets a value to the ViewModel property so it is never null."")]
    public partial class ");
            
            #line 245 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters> : ");
            
            #line 245 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write(@", INavigationView<TViewModel, TParameters>, ILifecycleViewModelOwner<TViewModel>
        where TViewModel : class, ILifecycleViewModelWithParameters<TParameters>
        where TParameters : Parameters
    {
        private TParameters? _parameters;

        /// <inheritdoc />
        public ");
            
            #line 252 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 254 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        public ");
            
            #line 258 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSCoder coder)\r\n            : base(coder)\r\n        {\r\n            LifecycleDeleg" +
                    "ate = new ViewLifecycleDelegate<");
            
            #line 261 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        public ");
            
            #line 265 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(string nibName, NSBundle bundle)\r\n            : base(nibName, bundle)\r\n        {" +
                    "\r\n            LifecycleDelegate = new ViewLifecycleDelegate<");
            
            #line 268 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        protected ");
            
            #line 272 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(NSObjectFlag t)\r\n            : base(t)\r\n        {\r\n            LifecycleDelegate" +
                    " = new ViewLifecycleDelegate<");
            
            #line 275 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        protected internal ");
            
            #line 279 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("(IntPtr handle)\r\n            : base(handle)\r\n        {\r\n            LifecycleDele" +
                    "gate = new ViewLifecycleDelegate<");
            
            #line 282 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(viewGenerationOptions.ClassName));
            
            #line default
            #line hidden
            this.Write("<TViewModel, TParameters>, TViewModel>(this);\r\n        }\r\n\r\n        /// <inheritd" +
                    "oc />\r\n        public event EventHandler<ResultSetEventArgs> ResultSet;\r\n\r\n     " +
                    "   /// <inheritdoc />\r\n        protected override IViewLifecycleDelegate Lifecyc" +
                    "leDelegate { get; }\r\n\r\n        /// <inheritdoc />\r\n        public TViewModel Vie" +
                    "wModel { get; private set; }\r\n\r\n        /// <inheritdoc />\r\n        public void " +
                    "SetParameters(TParameters? parameters)\r\n        {\r\n            _parameters = par" +
                    "ameters;\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public void SetResult" +
                    "(ResultCode resultCode, Result? result)\r\n        {\r\n            LifecycleDelegat" +
                    "e.SetResult(resultCode, result);\r\n        }\r\n\r\n        /// <inheritdoc />\r\n     " +
                    "   public void RaiseResultSet(ResultCode resultCode, Result? result)\r\n        {\r" +
                    "\n            ResultSet?.Invoke(this, new ResultSetEventArgs(resultCode, result))" +
                    ";\r\n        }\r\n\r\n        /// <inheritdoc />\r\n        public void HandleResult(obj" +
                    "ect sender, ResultSetEventArgs args)\r\n        {\r\n            if (sender == null)" +
                    "\r\n                throw new ArgumentNullException(nameof(sender));\r\n            " +
                    "if (args == null)\r\n                throw new ArgumentNullException(nameof(args))" +
                    ";\r\n\r\n            LifecycleDelegate.HandleResult(sender, args);\r\n        }\r\n\r\n   " +
                    "     /// <inheritdoc />\r\n        void ILifecycleViewModelOwner<TViewModel>.SetVi" +
                    "ewModel(TViewModel viewModel)\r\n        {\r\n            ViewModel = viewModel ?? t" +
                    "hrow new ArgumentNullException(nameof(viewModel));\r\n        }\r\n\r\n        /// <in" +
                    "heritdoc />\r\n        async Task ILifecycleViewModelOwner<TViewModel>.InitializeV" +
                    "iewModelAsync(bool recreated)\r\n        {\r\n            await ViewModel.Initialize" +
                    "Async(_parameters, recreated);\r\n        }\r\n    }\r\n}\r\n");
            
            #line 336 "C:\FlexiMvvm\FlexiMvvm.Generation\Views\Generation\Ios\ViewsGenerator.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ViewsGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
